### ISSUE TITLE
Removing stock apps + Bootloop after using Cydia Eraser [iPhone 6 - iOS 8.4.1]

### ISSUE THREAD

**Issue by CosmicEternityCD** [TheRealClarity/wtfis#1]
So after I installed a few tweaks on my iPhone 6, it removed some stock apps. So then I tried to use cydia eraser to start fresh. BIG MISTAKE. NOW ITS BOOTLOOPING.

**Comment by TheRealClarity** [comment]
At what point did it bootloop when running Eraser?

During the initial jailbreak process, did the phone reboot after about 7 seconds?

**Comment by TheRealClarity** [comment]
Closing since this has been attributed to factors outside the jailbreak itself.
