### ISSUE TITLE
Filza Issue 

### ISSUE THREAD

**Issue by Jefferyat** [TheRealClarity/wtfis#10]
I am trying to modify the com.apple.springboard.plist on my iPad Mini 2 running iOS 8.3 jailbroken with wtfis, and i did find the /var/mobile/Library/Preferences/com.apple.springboard.plist on my device but i do not see the SBShowNonDefaultSystemApps on my file

**Comment by Jefferyat** [comment]
Also can wtfis beta be updated to version 1.0

**Comment by Jefferyat** [comment]
when it releases

**Comment by TheRealClarity** [comment]
Not a wtfis issue. Please refer to the support server.
