### ISSUE TITLE
Jailbreak App Crashes

### ISSUE THREAD

**Issue by Jefferyat** [TheRealClarity/wtfis#2]
i tried out the wtfis jailbreak this morning on my iPad Air 1 on iOS 8.4.1 and it installed successfully and i opened the app and clicked on the go button and it rebooted the device and now every time i open the app it crashes every single time i open it, i've tried erasing the device uninstalling and reinstalling the app multiple times and it just crashes every single time i open the app

**Comment by TheRealClarity** [comment]
If the app crashes on launch, even after a reboot, you're still jailbroken.
Erasing all contents and settings instead of running Cydia Eraser is not intended and you'll still be jailbroken.

**Comment by Jefferyat** [comment]
But Cydia doesn't show up on my home screen

**Comment by TheRealClarity** [comment]
Can you try Cydia:// on Safari?

**Comment by Jefferyat** [comment]
That worked but only for a few minutes and then when I opened cydia:// in safari it rebooted my device and now when I use Cydia:// in safari it crashes every time

**Comment by TheRealClarity** [comment]
Try to reset home screen layout. Install openssh and run uicache.

**Comment by Cryptiiiic** [comment]
bro broke the number one rule of jailbreak smh my head...

**Comment by TheRealClarity** [comment]
Closing, assuming fixed.
