### ISSUE TITLE
32 bit support

### ISSUE THREAD

**Issue by K4sum1** [TheRealClarity/wtfis#3]
It would be nice to have a 8.x 32 bit untethered jailbreak using sock_port. If this is too much effort or not in the scope of this project, that's fine as older jailbreaks already exist, but it would be cool to have a unified 8.x jailbreak.

**Comment by Cryptiiiic** [comment]
I could look into this, keep in mind my only 8.x 32bit is my a5. @K4sum1

**Comment by TheRealClarity** [comment]
I'll speak with dora about it. Closing as it is not planned for wtfis for the time being.
