### ISSUE TITLE
Unable to boot

### ISSUE THREAD

**Issue by ItsOver23** [TheRealClarity/wtfis#5]
Hi, I have accidentally deleted the wtfis file which contains the untether files via ifile on my iPhone 6 running ios 8.3, Now it is stuck at the apple logo whenever I try to boot it. Any ways I can get it to boot while preserving the iOS version? Thank you very much.

**Comment by TheRealClarity** [comment]
You need to place the untether back using a SSH Ramdisk. Not a wtfis issue. Closing.

**Comment by ItsOver23** [comment]
> You need to place the untether back using a SSH Ramdisk. Not a wtfis issue. Closing.

How can I find the deleted file?
