### ISSUE TITLE
Cydia not working iPhone 5s ios 8.4.1

### ISSUE THREAD

**Issue by chetsplat** [TheRealClarity/wtfis#6]
So after installing wtfis the cydia app insta crashes every time i open it. Any fix for this?

**Comment by TheRealClarity** [comment]
Did it _ever_ work?
Did your phone reboot after jailbreaking with wtfis?

**Comment by chetsplat** [comment]
*i think i turned cydia on once and it was working and after a reboot it just like died  (also it did reboot, the wtfis app autocrashes when opened)

**Comment by TheRealClarity** [comment]
As long as the shared cache is patched, Cydia will be able to be launched (even without a jailbreak!). The wtfis app crashing shows you're successufly jailbroken and, as such, that the shared cache is patched correctly :/
I suppose you don't have openssh installed and I don't think you can do much besides installing and running Cydia Eraser in some way or another (use a ssh ramdisk to install it maybe or try to find out what's wrong that way?) or maybe sideloading Filza might work? There's not much I can do, sorry.

**Comment by chetsplat** [comment]
okay. Thank you for the advice for cydia eraser tho!
