### ISSUE TITLE
Cydia not showing up 

### ISSUE THREAD

**Issue by Jefferyat** [TheRealClarity/wtfis#9]
I Just Jailbroke a iPad Mini 2 running iOS 8.3 using wtfis and cydia did not show up on my home screen, i did NOT erase all content and settings when this happened, what i did is used cydia by opening up safari and searching cydia:// and it opened cydia, but Cydia or my Jailbreak apps are not showing up on my homescreen. any fixes??

**Comment by TheRealClarity** [comment]
Can you install openssh and mterminal, please?
Did you update any packages in Cydia? Did it try removing any package, if so?

**Comment by Anonzie** [comment]
Install MTerminal or Cydown, they auto run uicache during install.

**Comment by Jefferyat** [comment]
I did not update anything but one package in cydia and that was UIKit Tools

**Comment by Jefferyat** [comment]
I just installed openSSH and MTerminal from cydia and which packages do i need to update

**Comment by TheRealClarity** [comment]
Did wtfis reboot the device on initial jailbreak? Or did the app crash?
If it did reboot, please type
```
su
alpine
uicache
``` 
on mterminal. Let me know if the apps show up.
If the app crashed on initial install, don't do the above, let me know first.

**Comment by TheRealClarity** [comment]
uikit tools is the uicache package actually... Can you also check if you have patcyh installed? There might be some incompatibilities...

**Comment by Jefferyat** [comment]
it did reboot the device on initial jailbreak, and i did type su alpine and uicache in mterminal and cydia still did not show up on my home screen, and i did upgrade uikit tools in cydia and still cydia did not show up on my home screen, patcyh is installed on my device

**Comment by TheRealClarity** [comment]
mterminal shows up but not Cydia??

**Comment by Jefferyat** [comment]
Both MTerminal and Cydia dont show up

**Comment by TheRealClarity** [comment]
> it did reboot the device on initial jailbreak, and i did type su alpine and uicache in mterminal and cydia still did not show up on my home screen, and i did upgrade uikit tools in cydia and still cydia did not show up on my home screen, patcyh is installed on my device

How did you run the commands on mterminal if it doesn't show up?

**Comment by Jefferyat** [comment]
the commands i ran were

su
alpine
uicache 

didnt work, how i ran the commands were by going to safari and typing in mterminal://

**Comment by TheRealClarity** [comment]
ok I think I know the issue, you’ve been able to reproduce this in 2 different iPads, right?
When installing an App Store app, it shows up properly?

**Comment by Jefferyat** [comment]
yes, and appstore applications do show up but not JB apps

**Comment by Lawin0129** [comment]
The same exact thing happens to me on my iPad Mini 2 on iOS 8.1.3 and exclusively on my iPad Mini 2. I don't know why this occurs. I never was able to get Cydia or the jailbreak apps to appear at all.

**Comment by Lawin0129** [comment]
App store apps show up for me too

**Comment by TheRealClarity** [comment]
Can you install Filza and go into `/var/mobile/Library/Preferences/com.apple.springboard.plist` and change `SBShowNonDefaultSystemApps` to yes and check if it solved your issue?

**Comment by Lawin0129** [comment]
Whenever I add "SBShowNonDefaultSystemApps" it just gets removed

**Comment by TheRealClarity** [comment]
> Whenever I add "SBShowNonDefaultSystemApps" it just gets removed

Did you do it on the com.apple.springboard.plist or com.apple.Springboard.plist file? 
Also, did you add it as a boolean?

**Comment by Lawin0129** [comment]
There's no "com.apple.Springboard.plist" file but there is "com.apple.springboard.plist". I opened "com.apple.springboard.plist" in Filza and added "SBShowNonDefaultSystemApps" as a boolean and set it to "Yes". But whenever the system writes to the springboard plist, it removes "SBShowNonDefaultSystemApps".

**Comment by TheRealClarity** [comment]
Ok, figured it out on my end. Can you set it, save the file and then reboot your iPad? Once you boot, the setting should still be there. If necessary, also uicache.

**Comment by TheRealClarity** [comment]
Confirmed to fix the issue. Will ship on wtfis 1.0.
